import {
  SideBarAccountInfoItems,
  SidebarItems,
} from "@/types/sidebar.items.types";
import {
  BriefcaseBusiness,
  Footprints,
  Home,
  LayoutDashboard,
  PersonStanding,
  ScrollText,
  Shirt,
  Store,
  User,
} from "lucide-react";
import BrandImage from "@/../public/assets/logo/nike.jpg";

export const SideBarNavItems: SidebarItems = [
  {
    title: "Home",
    href: "/",
    icon: Home,
    subMenuViewName: undefined,
    disabled: false,
    isSubItem: false,
  },
  {
    title: "Brands",
    href: "/brands",
    subMenuViewName: "brands",
    icon: BriefcaseBusiness,
    disabled: false,
    isSubItem: true,
    SubItemsList: [
      {
        title: "Nike",
        href: "/brands/nike",
        icon: BriefcaseBusiness,
        disabled: false,
        brandImage: BrandImage.src,
      },
      {
        title: "Adidas",
        href: "/brands/adidas",
        icon: BriefcaseBusiness,
        disabled: false,
        brandImage: BrandImage.src,
      },
      {
        title: "Puma",
        href: "/brands/puma",
        icon: BriefcaseBusiness,
        disabled: false,
        brandImage: BrandImage.src,
      },
      {
        title: "Reebok",
        href: "/brands/reebok",
        icon: BriefcaseBusiness,
        disabled: false,
        brandImage: BrandImage.src,
      },
      {
        title: "New Balance",
        href: "/brands/new-balance",
        icon: BriefcaseBusiness,
        disabled: false,
        brandImage: BrandImage.src,
      },
      {
        title: "Under Armour",
        href: "/brands/under-armour",
        icon: BriefcaseBusiness,
        disabled: false,
        brandImage: BrandImage.src,
      },
      {
        title: "ASICS",
        href: "/brands/asics",
        icon: BriefcaseBusiness,
        disabled: false,
        brandImage: BrandImage.src,
      },
      {
        title: "Fila",
        href: "/brands/fila",
        icon: BriefcaseBusiness,
        disabled: false,
        brandImage: BrandImage.src,
      },
    ],
  },
  {
    title: "Sneakers",
    href: "/sneakers",
    subMenuViewName: "sneakers",
    icon: Footprints,
    disabled: false,
    isSubItem: true,
    SubItemsList: [
      {
        title: "Shoes",
        href: "/footwears/shoes",
        icon: BriefcaseBusiness,
        disabled: false,
      },
      {
        title: "Sandals",
        href: "/footwears/sandals",
        icon: BriefcaseBusiness,
        disabled: false,
      },
      {
        title: "Sneakers",
        href: "/footwears/sneakers",
        icon: BriefcaseBusiness,
        disabled: false,
      },
      {
        title: "Boots",
        href: "/footwears/boots",
        icon: BriefcaseBusiness,
        disabled: false,
      },
      {
        title: "Slippers",
        href: "/footwears/slippers",
        icon: BriefcaseBusiness,
        disabled: false,
      },
      {
        title: "Loafers",
        href: "/footwears/loafers",
        icon: BriefcaseBusiness,
        disabled: false,
      },
      {
        title: "Flip Flops",
        href: "/footwears/flip-flops",
        icon: BriefcaseBusiness,
        disabled: false,
      },
      {
        title: "Formal Shoes",
        href: "/footwears/formal-shoes",
        icon: BriefcaseBusiness,
        disabled: false,
      },
      {
        title: "Sports Shoes",
        href: "/footwears/sports-shoes",
        icon: BriefcaseBusiness,
        disabled: false,
      },
    ],
  },
  {
    title: "Apparel",
    href: "/apparel",
    subMenuViewName: "apparel",
    icon: Shirt,
    disabled: false,
    isSubItem: true,
    SubItemsList: [
      {
        title: "T-Shirts",
        href: "/topwear/t-shirts",
        icon: BriefcaseBusiness,
        disabled: false,
      },
      {
        title: "Shirts",
        href: "/topwear/shirts",
        icon: BriefcaseBusiness,
        disabled: false,
      },
      {
        title: "Jackets",
        href: "/topwear/jackets",
        icon: BriefcaseBusiness,
        disabled: false,
      },
      {
        title: "Hoodies",
        href: "/topwear/hoodies",
        icon: BriefcaseBusiness,
        disabled: false,
      },
      {
        title: "Sweatshirts",
        href: "/topwear/sweatshirts",
        icon: BriefcaseBusiness,
        disabled: false,
      },
      {
        title: "Polos",
        href: "/topwear/polos",
        icon: BriefcaseBusiness,
        disabled: false,
      },
      {
        title: "Tank Tops",
        href: "/topwear/tank-tops",
        icon: BriefcaseBusiness,
        disabled: false,
      },
      {
        title: "Blazers",
        href: "/topwear/blazers",
        icon: BriefcaseBusiness,
        disabled: false,
      },
    ],
  },
  {
    title: "Accessories",
    href: "/accessories",
    subMenuViewName: "accessories",
    icon: PersonStanding,
    disabled: false,
    isSubItem: true,
    SubItemsList: [
      {
        title: "Caps & Hats",
        href: "/accessories/caps-hats",
        icon: BriefcaseBusiness,
        disabled: false,
      },
      {
        title: "Socks",
        href: "/accessories/socks",
        icon: BriefcaseBusiness,
        disabled: false,
      },
      {
        title: "Bags & Backpacks",
        href: "/accessories/bags-backpacks",
        icon: BriefcaseBusiness,
        disabled: false,
      },
      {
        title: "Belts",
        href: "/accessories/belts",
        icon: BriefcaseBusiness,
        disabled: false,
      },
      {
        title: "Wallets",
        href: "/accessories/wallets",
        icon: BriefcaseBusiness,
        disabled: false,
      },
      {
        title: "Sunglasses",
        href: "/accessories/sunglasses",
        icon: BriefcaseBusiness,
        disabled: false,
      },
      {
        title: "Watches",
        href: "/accessories/watches",
        icon: BriefcaseBusiness,
        disabled: false,
      },
      {
        title: "Scarves",
        href: "/accessories/scarves",
        icon: BriefcaseBusiness,
        disabled: false,
      },
      {
        title: "Gloves",
        href: "/accessories/gloves",
        icon: BriefcaseBusiness,
        disabled: false,
      },
      {
        title: "Jewelry",
        href: "/accessories/jewelry",
        icon: BriefcaseBusiness,
        disabled: false,
      },
    ],
  },
  {
    title: "Orders",
    href: "/orders",
    icon: ScrollText,
    disabled: false,
    isSubItem: false,
    subMenuViewName: undefined,
  },
  {
    title: "Profile",
    href: "/profile",
    icon: User,
    isSubItem: false,
    subMenuViewName: undefined,
    disabled: false,
  },
];
